# Generated by Django 5.2.10 on 2026-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='До 160 символов', max_length=160),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='До 60 символов', max_length=60),
        ),
    ]
