# Generated by Django 5.2.10 on 2026-01-22 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Уровень (A1, A2, B1...)')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип слова')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тип слова',
                'verbose_name_plural': 'Типы слов',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Слово')),
                ('translation', models.CharField(max_length=255, verbose_name='Перевод')),
                ('plural_form', models.CharField(blank=True, max_length=255, verbose_name='Множественное число')),
                ('conjugation', models.TextField(blank=True, verbose_name='Спряжения')),
                ('example', models.TextField(blank=True, verbose_name='Пример использования')),
                ('example_translation', models.TextField(blank=True, verbose_name='Перевод примера')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='dictionary.level', verbose_name='Уровень')),
                ('word_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='words', to='dictionary.wordtype', verbose_name='Тип слова')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['text'],
                'unique_together': {('text', 'word_type')},
            },
        ),
    ]
