# Generated by Django 5.2.10 on 2026-01-17 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_useranswer_answered_at_useranswer_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.examattempt', verbose_name='Попытка экзамена'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.answer', verbose_name='Выбранный ответ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test', verbose_name='Тест'),
        ),
    ]
