# Generated by Django 5.2.10 on 2026-01-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_useranswer_answered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='yes_no_answer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ Да/Нет'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.answer', verbose_name='Выбранный ответ'),
        ),
    ]
