# Generated by Django 5.2.10 on 2026-01-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_useranswer_yes_no_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Текст ответа'),
            preserve_default=False,
        ),
    ]
