# Generated by Django 5.2.10 on 2026-01-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_answer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
    ]
