# Generated by Django 5.2.10 on 2026-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_answer_text_alter_answer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
