# Generated by Django 5.2.10 on 2026-01-19 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_questiontext_alter_question_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontext',
            options={'verbose_name': 'Текст вопроса', 'verbose_name_plural': 'Тексты вопросов'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_texts', to='tests.questiontext', verbose_name='Вопрос'),
        ),
    ]
