# Generated by Django 5.2.10 on 2026-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_questiontext_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='До 160 символов', max_length=160),
        ),
        migrations.AddField(
            model_name='exam',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='До 60 символов', max_length=60),
        ),
    ]
