# Generated by Django 5.2.10 on 2026-02-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_examlevel_slug_testcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examlevel',
            name='slug',
        ),
    ]
