# Generated by Django 5.2.10 on 2026-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_examlevel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Полное описание категории'),
        ),
    ]
