# Generated by Django 5.2.10 on 2026-03-01 13:55

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_testcategory_full_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название части')),
                ('description', models.TextField(blank=True, verbose_name='Описание части')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст статьи')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('yes_no', 'Да / Нет'), ('multiple_choice', 'Выбор из вариантов'), ('text_without_answer', 'Просто текст')], default='multiple_choice', max_length=20, verbose_name='Тип теста'),
        ),
        migrations.AddField(
            model_name='test',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tests.testpart', verbose_name='Часть'),
        ),
    ]
