# Generated by Django 5.2.10 on 2026-03-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_testpart_alter_test_test_type_test_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpart',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.examlevel', verbose_name='Уровень'),
        ),
    ]
