# Generated by Django 5.2.10 on 2026-03-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_testpart_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpart',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams_1', to='tests.examlevel', verbose_name='Уровень'),
        ),
    ]
