# Generated by Django 5.2.10 on 2026-03-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_alter_testpart_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.testcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='testpart',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.examlevel', verbose_name='Уровень'),
        ),
    ]
