# Generated by Django 5.2.10 on 2026-03-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_testpart_category_alter_testpart_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpart',
            name='sequence_number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
